context: talos-k8s-proxmox
contexts:
    talos-k8s-proxmox:
        endpoints:
            - api.cluster.local
        ca: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJQekNCOHFBREFnRUNBaEVBdUMrVEJpeUl6amZzY2hSR21wWHE1REFGQmdNclpYQXdFREVPTUF3R0ExVUUKQ2hNRmRHRnNiM013SGhjTk1qWXdNVEl6TVRVeE9ESTRXaGNOTXpZd01USXhNVFV4T0RJNFdqQVFNUTR3REFZRApWUVFLRXdWMFlXeHZjekFxTUFVR0F5dGxjQU1oQUQvY0VYWEtjV2U0VkQ2NzNxejNBc2ljMVlxbDR3YmQ4Y1dpCnAxYStaeldlbzJFd1h6QU9CZ05WSFE4QkFmOEVCQU1DQW9Rd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUcKQ0NzR0FRVUZCd01DTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRk9RMTNsbDdUbWtwU0NOZApCbHR5NXVlVlBISEtNQVVHQXl0bGNBTkJBTHNpaFJuNHVmQjZuQ0dYQlRyTDAxdjZQTGR1ZUVlY3VDZXlYQVAvCmtlSkxGeTZCdEtQSVlTYktXQWJieitSN0FWOUdCTlM2MXIweUpXNmhFWkVqT3c0PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJLVENCM0tBREFnRUNBaEVBdkI3SnNPZ1NHSEZuaStWYnI0ZUtOVEFGQmdNclpYQXdFREVPTUF3R0ExVUUKQ2hNRmRHRnNiM013SGhjTk1qWXdNVEl6TVRVeE9ESTRXaGNOTWpjd01USXpNVFV4T0RJNFdqQVRNUkV3RHdZRApWUVFLRXdodmN6cGhaRzFwYmpBcU1BVUdBeXRsY0FNaEFMVHd0NDZ2MzZGN25ORkhnNFdTYWppdHduY3Q5TlZuCmhRVnBja3cvRWFQK28wZ3dSakFPQmdOVkhROEJBZjhFQkFNQ0I0QXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0h3WURWUjBqQkJnd0ZvQVU1RFhlV1h0T2FTbElJMTBHVzNMbTU1VThjY293QlFZREsyVndBMEVBalFpOAoycGp0NEs2dzRYQmhieFpQTXR2L0p2dDZTNkdtaFUvd3RLNk4zekg2WlFSaWJUaDhadWwvRjRZRUs0V05UU3NxCm9UMGtNK2doODNacE9pMFVEZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        key: ENC[AES256_GCM,data:J/52WHlDPXww5sB1fEkmJgoppys4riAxCUIHEiluOILD+XZhd0mIQvnCuy6KJj8340EnuI2qRJolJY6VyOWJpB7uAZ6cMFNWyFwa93kFUaIo2T56bhakpzptG0tQjgxpT7yVQB8gL0GmpDVxWHuvUYcabdMRiHA6OMSGsZQIu2mv4Obz7M41oQVX/UBX0p9WoudCHwIGXYJo0LcVSXlv7kYGVYXjNvU4xvD5wl+akorLlrbA,iv:nD+vbR8ft+u6ogTdTkmBV0YAWmI3O4uOzNRJeKfVSw8=,tag:mxAE4x2ffWbjZX1VlX+ucg==,type:str]
sops:
    age:
        - recipient: age1ngvggfld4elq68926uczkes9rcqfjhnqn0tr6l8avyp4h46qzucqvx3sdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ZHd6enp4SHQxUUVWOFU5
            Z1lvZ1VtdG5qMFlTSE5UTDlkcTBhbXRVcW53CnNKOWVFd3NxSE94TE42Y1d3TEg2
            OUliK1NpTU9velpMT09USFRUY0NxZlUKLS0tIDlvQjd5TC8rek1Eb21BWWt2dWJR
            T0dDY2c1MjFaa0NZZW84dXBxcGZudzAKy+A46nfNgB2Ef2izJifoj7GWnKxSvSo4
            Vx7gwZYMdv4/sSC9bNWAlScOm4qbHaXjoRi04Qm+xlkexAFBR3Tgbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T15:19:45Z"
    mac: ENC[AES256_GCM,data:Q29YdzRP8aaHFe79o0gKe0UKkurqngPC3QxbmV3eNIl295K/hQiF2RD8wlkaGDlwOnpspMuhoP4flhMqQC/kqKfgOru8dI8JUI0HAkJX8o5xnr2KkkJoSYNpLcLsAelBQnduoz28QNPVtls9xCN3TBiSWnq98aUZRw3IFvzxvF8=,iv:Ytw0x9cbDv0gWdgIWI/XKvNQnT7l3b/OUkClyUWq9q8=,tag:M13yPplcrxpc5VdRaOQJ4w==,type:str]
    encrypted_regex: key
    version: 3.11.0
